name: Tesla External Adapter
description: An external adapter to connect to a Tesla vehicle or Tesla Powerwall
node_identifier: tesla-external-adapter
platforms:
  - AWS Lambda
  - GCP Functions
  - Docker
  
